name: Semgrep CE Scan

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "17 5 * * 4"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    container:
      image: semgrep/semgrep
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Semgrep Community Edition scan
        run: semgrep scan --config auto .
